### ISSUE TITLE
Misc

### ISSUE THREAD

**Issue by yahgwai** [anydotcrypto/cyberdice#1]
* We should put the contract addresses on the home page - and a link to contract code probs too

**Comment by stonecoldpat** [comment]
Yup. All here:
https://etherscan.io/address/0x2542f9c01b9a1Dfb26aB56Bc246E67058F4A0d10 

Updated link on website.

**Comment by yahgwai** [comment]
-- Cyberdice instructions
- [ ] Before installing npm we should be instructed to clone this repo.
- [ ] The get-npm link should just be: https://nodejs.org/en/ since that's where it redirects to anyway
- [ ] put // fill in the blanks on a new line in this statement:
```
// const { relayTx, anySenderReceipt } = await sendToAnySender(// fill in the blanks);
```
eg 
```
// const { relayTx, anySenderReceipt } = await sendToAnySender(
// // fill in the blanks
//);
```
so that when uncommented the typescript on the page doesnt give loads of errors because of an unclosed brace
- [ ] I think we need to do something better with console.log - since ppl will probably use it for debugging, maybe something like:
```
console.log = (messages) => {
    if(messages === "ABI blah blah prpolem") return;
    else console.log(messages);
} 
```
- [ ] Add a link to our main docs website
- [ ] I find the "All tickets" message at the end confusing, I always think it refers to my tickets. Maybe just remove it? We have the total on the website.
- [ ] It appears that the sections in submitTicket that should be commented out are actually already uncommented: https://github.com/anydotcrypto/cyberdice/blob/master/src/ts/submitTicket.ts#L120
- [ ] typo: "CyberDice, s ocheck out the getNoTickets"


-- Website
- [ ] The website should also include a link to our telegram

**Comment by stonecoldpat** [comment]
-- Cyberdice instructions

[x] Before installing npm we should be instructed to clone this repo.
[x]  The get-npm link should just be: https://nodejs.org/en/ since that's where it redirects to anyway
[x] put // fill in the blanks on a new line in this statement:
// const { relayTx, anySenderReceipt } = await sendToAnySender(// fill in the blanks);
eg

// const { relayTx, anySenderReceipt } = await sendToAnySender(
// // fill in the blanks
//);
so that when uncommented the typescript on the page doesnt give loads of errors because of an unclosed brace

[x] I think we need to do something better with console.log - since ppl will probably use it for debugging, maybe something like:
console.log = (messages) => {
    if(messages === "ABI blah blah prpolem") return;
    else console.log(messages);
} 
[x] Add a link to our main docs website
[x]  I find the "All tickets" message at the end confusing, I always think it refers to my tickets. Maybe just remove it? We have the total on the website.
[x] It appears that the sections in submitTicket that should be commented out are actually already uncommented: https://github.com/anydotcrypto/cyberdice/blob/master/src/ts/submitTicket.ts#L120


 [x] typo: "CyberDice, s ocheck out the getNoTickets"
-- Website

 [x] The website should also include a link to our telegram
